# Generated by Django 5.0.2 on 2024-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Дата производства продукта'),
        ),
    ]
