# Generated by Django 4.2.2 on 2024-03-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_photo', verbose_name='фото')),
                ('price', models.IntegerField(verbose_name='Цена за покупку')),
                ('created_at', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Дата создания (записи в БД)')),
                ('updated_at', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Дата последнего изменения (записи в БД)')),
                ('manufactured_at', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Дата производства продукта')),
                ('view_counter', models.PositiveIntegerField(default=0, help_text='Укажите кол-во просмотров', verbose_name='Счетчик Проcмотров')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер версии')),
                ('nomination', models.CharField(max_length=50, verbose_name='название')),
                ('is_current', models.BooleanField(default=True, verbose_name='текущая')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
