# Generated by Django 5.0.2 on 2024-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Дата создания (записи в БД)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Дата последнего изменения (записи в БД)'),
        ),
    ]
