# Generated by Django 4.2.2 on 2024-03-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product', 'number', 'nomination', 'is_current'), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
