# Generated by Django 5.0.2 on 2024-03-19 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='name_ver',
        ),
        migrations.RemoveField(
            model_name='version',
            name='number_ver',
        ),
        migrations.RemoveField(
            model_name='version',
            name='sign_ver',
        ),
        migrations.AddField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='текущая'),
        ),
        migrations.AddField(
            model_name='version',
            name='nomination',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='number',
            field=models.IntegerField(default='', verbose_name='номер версии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='view_counter',
            field=models.PositiveIntegerField(default=0, help_text='Укажите кол-во просмотров', verbose_name='Счетчик Проcмотров'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product', verbose_name='Product'),
        ),
    ]
